### ISSUE TITLE
[Command failed: fd --type f --hidden --follow --exclud...

### ISSUE THREAD

**Issue by AdamBD** [junegunn/fzf.vim#1296]
- [X] I have fzf 0.23.0 or above
- [X] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [X] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md
- [X] I have read through the manual page of fzf (`man fzf`)
- [X] I have searched through the existing issues

The following is my FZF default command: `let $FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'`

I get the following error: `[Command failed: fd --type f --hidden --follow --exclud`

Have the following plugs and the latest version of everything. 
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }

Was working fine till I ported to a new mac.

thoughts?

**Comment by tabiva** [comment]
Same issue here, but I get this errors only inside tmux.

**Comment by junegunn** [comment]
Is fd installed?

**Comment by sahilrajput03** [comment]
I am facing same issue on archlinux:

```
SYSTEM          : Linux arch-os 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64 GNU/Linux
HOSTNAME        : arch-os
UPTIME          :  23:51:38 up 1 day,  5:20,  1 user,  load average: 1.46, 1.71, 1.69
DISK            : /dev/sdb4      138512180 54711552  76691748  42% /home
HOSTNAMECTL     :
 Static hostname: arch-os
       Icon name: computer-laptop
         Chassis: laptop 💻
      Machine ID: 2a33fcd86a7c4d46b6a9b387c8ac6c4d
         Boot ID: b83997b5488448a4a8bd1afe9650aed5
Operating System: Arch Linux
          Kernel: Linux 5.16.5-arch1-1
    Architecture: x86-64
 Hardware Vendor: HP
  Hardware Model: HP Notebook
```

Any possible fix i can try to fix this..

**Comment by junegunn** [comment]
Is the command in the error message (which should be your `$FZF_DEFAULT_COMMAND`) valid?
Does it work as expected on your shell?

**Comment by sahilrajput03** [comment]
@junegunn 

I think from this, I can not say how it should work but it gives that output as you suggested to try.

![image](https://user-images.githubusercontent.com/31458531/153216088-f5a20fb2-5820-4870-8d7c-b18a5115b1e5.png)

**Comment by sahilrajput03** [comment]
FYI: I FIXED THIS ISSUE BY INSTALLING `proximity-sort` package on my archlinux. [Source](https://aur.archlinux.org/packages/proximity-sort) of installation.

I could see this is the error is bcoz of `proximity-sort` bcoz vim was showing some command like:
`Command failed: fd --type f --hidden --follow --exclud.... | proximity-sort ....` and I tried to run `proximity-sort` on my terminal and it said `bash: proximity-sort: command not found`.

Thanks to @junegunn .., I fixed this issue!! :)

**Comment by sahilrajput03** [comment]
@AdamBD Can you try installing `proximity-sort` package somehow on your linux..? 

**I 99% sure that it'll work!**

**Comment by mattcargile** [comment]
This is still broken for me on _Windows_. My `$env:FZF_DEFAULT_COMMAND = 'fd.exe'` fails.

**Comment by Yuandandi** [comment]
You can find it on the readme.

Note that the binary is called fdfind as the binary name fd is already used by another package. It is recommended that after installation, you add a link to fd by executing command ln -s $(which fdfind) ~/.local/bin/fd, in order to use fd in the same way as in this documentation. Make sure that $HOME/.local/bin is in your $PATH.
