### ISSUE TITLE
Terminal buffer doesn't close

### ISSUE THREAD

**Issue by rivertam** [junegunn/fzf.vim#449]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim

Hi, so I just ported my init.vim over from another computer, and I seem to have pretty much everything working. I may have missed an installation step, but I can't figure out what it is. Meanwhile, I can reproduce this issue with the `vim -Nu <(curl...)` command (it's actually worse like that), but there's a decent chance it's a missing binary or something.

So when I open `:Files`, I see the file list as I'm used to and everything seems to be working fine. However, when I press enter on a file, the buffer just goes blank and is still in terminal mode. When I quit out of neovim, I get this:

![2017-58-18_16-58-04](https://user-images.githubusercontent.com/4165105/30564301-947f192e-9c92-11e7-8ab1-222befde0595.png)

This leads me to believe that the terminal buffer is not being exited properly.

Is this something I'm doing wrong or is it an issue with fzf.vim? If it's relevant, I'm using https://github.com/sharkdp/fd as my find command, but when I take that line out the behavior does not change.

Everything was literally installed today, as this is a brand new computer running Ubuntu 16.04.

**Comment by junegunn** [comment]
I've never experienced this. This could be an issue of Neovim, which version of Neovim are you running? (`:version`)

**Comment by junegunn** [comment]
Well, I just built Neovim from the latest source, but I can't reproduce the problem. I'm not sure what went wrong with your setup. Do you have the same issue on regular vim?

**Comment by rivertam** [comment]
Doesn't seem like it. Sometimes it does work in neovim, but it's under 50% of the time. I just tried about five times using vim and I had no issues, so I guess it must be neovim specific, and probably specific to my particular machine as well.

**Comment by rivertam** [comment]
This is pretty random, but I discovered that if I do `bd!` on the blank terminal that's left over, I get no file, but fzf.vim works properly for the rest of the session until I restart nvim.

**Comment by virus-found** [comment]
I confirm this in vim 8.0.1274

How to reproduce:
* `:Files`
* new terminal split appears (because I use `let g:fzf_layout = { 'window': '20split enew' }`)
* press enter on any search result here
* the file is opened
* the terminal split is emptied and still open, its title says `!sh [finished][-]`

**Comment by joereynolds** [comment]
I also get this issue on the latest Neovim (0.2.1).
It did not happen on Neovim 0.2 for me

**Comment by junegunn** [comment]
Have you tried consulting Neovim team?

**Comment by rivertam** [comment]
@junegunn I'll file an issue there. In the meantime, do you have any advice as to how one might go about exploring the issue further/deeper? I'm not great at vim internals or vim debugging. I appreciate your time.

**Comment by junegunn** [comment]
I'm not familiar with nvim internals at all.

**Comment by josemarluedke** [comment]
I'm having a similar issue with NeoVim v0.2.1.

**Comment by rivertam** [comment]
It looks like this was resolved in #1172, and I just realized I haven't seen this in months. Great work, and thanks so much @ronmrdechai!

**Comment by bryanalves** [comment]
This is still happening to me on neovim, but not vim8:

* neovim 0.3.4
* vim 8.1
* fzf b31512e2a2d062ee4b6eb38864594c83f1ad2c2f

**Comment by m-novikov** [comment]
So for me problem and solution was the same as described in this [comment ](https://github.com/junegunn/fzf.vim/issues/544#issuecomment-457456166). Except the offending mapping looked like this:
```vim
tnoremap <C-[> <C-\><C-N>
```
which is essentially the same as
```vim
tnoremap <ESC> <C-\><C-N>
```

**Comment by AeonFr** [comment]
For me this seems to be related with other plugins, possibly CoC. It's also a neovim-only issue

If I save a `.ts` file and immediately open FZF (`:Files`), when CoC finishes doing the process in the background, it focuses on the editor window. From now on, the FZF window is impossible to close unless exiting vim (`:q!`), or creating a new tab and using `:tabclose` on the old one. (Opening fzf again won't close it for example, and neither `ESC` or `Ctrl \ + Ctrl n`)

For now I fixed this issue adding this to my neovim config (disables floating window):

```
let g:fzf_layout = { 'down': '~40%' }
```
