### ISSUE TITLE
fzf gives empty buffer on :GFiles, :Files, :Ag etc..

### ISSUE THREAD

**Issue by joereynolds** [junegunn/fzf.vim#505]
- Category
    - [ ] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [ ] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [ ] Vim
    - [x] Neovim (v.0.2.1)

(Starting with the minimal configuration above crashed Neovim).

Hi!

I've just upgraded from Neovim v0.2.0 to v0.2.1, since the upgrade, the first command I give to fzf when I enter vim results in an empty buffer.

I've attached a gif of the problem.

This happens on all the fzf commands that I've tried.

### Steps to reproduce

- Open vim
- `:GFiles`
- Select an entry
- You'll get an empty buffer
- `<esc>`
- `:GFiles`
- Now your buffer is populated

I did used to get this bug in original vim 7.4, however I switched to Neovim, the problem was fixed until the upgrade.

![gif](https://user-images.githubusercontent.com/9536682/32826800-b8d561ee-c9e1-11e7-8d49-ddfe27c305ff.gif)

**Comment by justinmk** [comment]
> Starting with the minimal configuration above crashed Neovim).

Crash would be a Nvim bug. But that should be fixed already on 0.2.2 (master).

**Comment by joereynolds** [comment]
I tried the nvim.appimage of the nightly build and it still persists :(
I'll also raise a bug with Neovim

**Comment by danihodovic** [comment]
^ Same

**Comment by justinmk** [comment]
> I tried the nvim.appimage of the nightly build and it still persists :(

What is "it"? You mentioned a crash. Does it still happen? What's the exact message? Can you post a stacktrace?

**Comment by joereynolds** [comment]
Sorry, bad choice of wording. It (Neovim) doesn't crash, the empty buffer bug still persists on the latest appimage though.

**Comment by danihodovic** [comment]
@joereynolds Do you get the same issue as I described here: https://github.com/neovim/neovim/issues/7620 ?

**Comment by joereynolds** [comment]
@danihodovic from the wording of that my issue is different but probably related.
If I open Nvim and then use any of the commands, after hitting <cr> it opens an empty bufferr.
I have to re-run the command for it to work.

This only happens once. Once I have 're-ran' the command, it all works as normal

**Comment by joereynolds** [comment]
As an update, @danihodovic had done some investigation and managed to track it down to the nvim.appimage causing the problems (It has no problems if built from source apparently).

It was suggested that it's probably some internal state inside fzf that is causing this to happen.

**Comment by chipsenkbeil** [comment]
Was this supposed to be fixed with neovim 0.3.0's appimage? Not sure on the status. I still have this issue with trying the latest appimage.

**Comment by joereynolds** [comment]
@chipsenkbeil no idea, I compile nvim from source these days. If I get the chance, I'll try the image tomorrow

**Comment by joereynolds** [comment]
@chipsenkbeil I tried it the latest appimage and it still has the bug

**Comment by chipsenkbeil** [comment]
What can I do to help here? Is this something that could be fixed through FZF? Or is this entirely on the appimage?

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/8104 was fixed in Nvim 0.3.1 (prerelease).

**Comment by stsewd** [comment]
@justinmk big thanks!

**Comment by justinmk** [comment]
@Devligue Note that `NVIM v0.3.1-113-gda6874a7b` contains the SHA. https://github.com/neovim/neovim/commit/da6874a7b is before 
https://github.com/neovim/neovim/commit/4874214139ab86f7033d5e6c602f7515ed813443, so it's impossible for the fix to exist on the version you're using.

**Comment by Devligue** [comment]
Oh, I see now, thanks! I just thought that in your previous comment you said it *was fixed in Nvim 0.3.1 (prerelease).*

**Comment by justinmk** [comment]
It _was_ fixed in _Nvim 0.3.1 (prerelease)_. You have an older prerelease than the prerelease in which it was fixed. There are zillions of prereleases, so one must compare the SHA given by `:version`.

**Comment by Devligue** [comment]
Once again, thanks for clarification.
