### ISSUE TITLE
Search fzf command on path and source it their for the rtp via this plugin

### ISSUE THREAD

**Issue by olbrew** [junegunn/fzf.vim#60]
I prefer keeping my tools organised with Homebrew and not unnecessarily polluting my home directory. 
But when I install `FZF` via Homebrew it can't easily be used in vim.
We have to manually add Homebrew's versioned dir  `/usr/local/Cellar/fzf/'version'` (and thus change it after every update) to the `rtp`.

I understand this is not supposed to be a "flexible or configurable plugin" but this seems like a reasonable request as everyone who's not going to use the default location is going to have this problem if I'm right.
Or could you point me in the right direction to change this for myself?
Thank you.

**Comment by junegunn** [comment]
So I don't use Homebrew :)
fzf is not a vim plugin but I always use it in vim so I have no problem to have my vim plugin manager install it and I quite like the approach.

But anyway if you prefer Homebrew to install fzf, a couple approaches come to my mind.

1. With `brew install --HEAD fzf`, the path is fixed to `/usr/local/Cellar/fzf/HEAD`, which makes it easier to manager your `&rtp`
2. With `greadlink` installed from `brew install coreutils`, you can add the line to your `.vimrc`

```vim
execute 'set rtp+='.fnamemodify(systemlist('greadlink -f $(which fzf)')[0], ':h:h')
```

Makes sense?

**Comment by olbrew** [comment]
Yes, thank you. Reinstalling with `--HEAD` actually made me realise that, as stated in the caveats, I could just use `/usr/local/opt/fzf` for the runtime path :).

**Comment by olbrew** [comment]
I guess you can close this issue now, though I still think it would be a worthwhile addition to the plugin to search the $PATH for the `fzf` executable and set the vim rtp accordingly. This would spare everyone some configuration :smiley:

**Comment by junegunn** [comment]
Ah, right, I forgot. Even without `--HEAD` the path is fixed to `/usr/local/opt/fzf`. So I think it's a non-issue. I have mixed feelings about automatic detection of vim plugin relative to fzf executable, since one can simply download the binary without the auxiliary files. But I'll think about it. Thanks.

**Comment by rosshadden** [comment]
I have added `/usr/bin` to my `rtp`, which is where `fzf` gets installed from `pacman` on Arch Linux, but I still get the error.

The `rtp` entry is the folder containing the `fzf` binary, correct?  Or is it a path to the binary itself?  The path @olbrew uses is ambiguous to a non-homebrew user, but an easy answer for either of you.

**Comment by olbrew** [comment]
@rosshadden Neither. `/usr/local/opt/fzf/` contains the `bin` directory which contains the `fzf` binary. For reference it contains these files with me:

```
CHANGELOG.md
INSTALL_RECEIPT.json
LICENSE
README.md
bin
install
plugin
share
shell
uninstall
```

**Comment by rosshadden** [comment]
Oh, so the `rtp` path is supposed to point to a folder that contains a `bin` directory and `bin/fzf`.  That's... really weird.  I'll try just `/usr`, since that has `bin/fzf`.  (I have no `/usr/local/opt` dir.  Like I said, `fzf` is installed at `/usr/bin/fzf`).

Thanks!

**Comment by junegunn** [comment]
@rosshadden 

> rtp path is supposed to point to a folder that contains a bin directory and bin/fzf

No. It has to be the directory that contains `plugin/fzf.vim`, it's the standard vim plugin laytout. If you're not familiar with Vim plugins, I suggest you take a look at a plugin managers like vim-plug.

```vim
Plug 'junegunn/fzf'
```

The vim plugin of fzf will find the binary on your `$PATH`, or download it for you if it's not found.

**Comment by rosshadden** [comment]
@junegunn I thought what you said would be true, too, but including the `fzf` plugin doesn't actually work, despite `fzf` being a binary in `$PATH`.  I can only get `fzf.vim` working if I give it a local dir and tell it to run `./install --bin`, which means I have two `fzf` bins on my system.  I'm trying to avoid that and only have the system-level one.

At this point I should probably make a new issue instead of hijacking this one, I had thought at the time it would be a quick question.

**Comment by junegunn** [comment]
@rosshadden 

>  the fzf plugin doesn't actually work, despite fzf being a binary in $PATH

You sure about that? I just tested and it worked just as expected. This is the code that uses `fzf` that is found on the path.

https://github.com/junegunn/fzf/blob/b4c4a642eda9b34bc417b0cc988e3b158080be33/plugin/fzf.vim#L35-L38

Check the output of `:echo executable('fzf')`.

**Comment by rosshadden** [comment]
`:echo executable('fzf')` returns `1`, but I get `Unknown function: fzf#run` when running `:Ag`.

**Comment by junegunn** [comment]
@rosshadden There are two separate issues. 1. If `echo executable('fzf')` returns 1, the vim plugin of fzf will use it. You don't need to run the install script. 2. `Unknown function: fzf#run` means that the vim plugin file is not correctly registered to Vim.

1. Install fzf binary with whatever package manager you use. I don't know if it distributes [`plugin/fzf.vim` file](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim) with it or not, so I can't tell which directory you should add to your `&rtp`.
2. Use vim-plug to set up `&rtp` instead. With no `do` option (as in README), it will not run the install script and simply pick up the fzf binary found on your `$PATH`.

```vim
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
```

**Comment by rosshadden** [comment]
Well that's odd... I literally did nothing different since last time I tried, except for updating my system packages (so possibly `fzf`).  And it's all working now.  Vim and nvim are using my system binary.  I swear this didn't work the other day, but as long as it's working now I'm happy.

Thanks!
